# Generated by Django 6.0.5 on 2026-05-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_castingstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_worker', models.CharField(max_length=100)),
                ('sent_quantity', models.IntegerField()),
                ('received_quantity', models.IntegerField(default=0)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
