# Generated by Django 6.0.5 on 2026-05-11 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_weight_per_piece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='job_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.worker'),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_with_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='process',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rate_per_piece',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight_per_piece',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
