# Generated by Django 6.0.5 on 2026-05-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_item_type_item_job_worker_item_lot_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='job_worker',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='stage',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='lot_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('casting_entry', 'Casting Entry'), ('machining_issue', 'Machining Issue'), ('machining_receive', 'Machining Receive'), ('polishing_issue', 'Polishing Issue'), ('polishing_receive', 'Polishing Receive'), ('dispatch', 'Dispatch')], default='casting_entry', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='process',
            field=models.CharField(blank=True, choices=[('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_transactions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_transactions', to='inventory.warehouse'),
        ),
    ]
