# Generated by Django 6.0.5 on 2026-05-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_warehouse_remove_item_job_worker_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "process",
                    models.CharField(
                        choices=[
                            ("machining", "Machining"),
                            ("polishing", "Polishing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
