# Generated by Django 6.0.5 on 2026-05-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_jobworker"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="job_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.jobworker",
            ),
        ),
    ]
