# Generated by Django 6.0.5 on 2026-05-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_weight_per_piece_item_casting_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='default_machining_jobworker',
        ),
        migrations.RemoveField(
            model_name='item',
            name='machining_rate',
        ),
        migrations.CreateModel(
            name='ItemWorkerAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_piece', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_allocations', to='inventory.item')),
                ('job_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_allocations', to='inventory.jobworker')),
            ],
            options={
                'unique_together': {('item', 'job_worker')},
            },
        ),
    ]
