# Generated by Django 6.0.5 on 2026-05-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_stocktransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="job_worker",
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(default="REGULAR", max_length=100),
        ),
        migrations.AlterField(
            model_name="itemworkerallocation",
            name="job_worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_allocations",
                to="inventory.worker",
            ),
        ),
    ]
