# Generated by Django 6.0.5 on 2026-05-15 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_itemworkerallocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='process',
            field=models.CharField(blank=True, choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobworker',
            name='process',
            field=models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='process',
            field=models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50),
        ),
        migrations.CreateModel(
            name='LaborPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('SALARY', 'Salary'), ('ADVANCE', 'Advance'), ('JOB_WORK', 'Job Work Payment')], max_length=20)),
                ('payment_mode', models.CharField(default='CASH', max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.jobworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20)),
                ('overtime_hours', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='inventory.worker')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
