# Generated by Django 6.0.5 on 2026-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_item_process_alter_jobworker_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='daily_rate',
            field=models.FloatField(default=0),
        ),
    ]
