# Generated by Django 6.0.5 on 2026-05-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_worker_daily_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="monthly_fixed_salary",
            field=models.FloatField(
                default=0, help_text="Fixed monthly salary for Fixed model"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="overtime_rate",
            field=models.FloatField(default=0, help_text="Rate per hour of overtime"),
        ),
        migrations.AddField(
            model_name="worker",
            name="salary_model",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily Wage"),
                    ("FIXED", "Monthly Fixed"),
                    ("HOURLY", "Hourly/Time Based"),
                ],
                default="DAILY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="daily_rate",
            field=models.FloatField(
                default=0, help_text="Rate per day for Daily Wage workers"
            ),
        ),
    ]
