# Generated by Django 6.0.5 on 2026-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_worker_monthly_fixed_salary_worker_overtime_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='identity_number',
            field=models.CharField(blank=True, help_text='Aadhar / Govt ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='standard_shift_hours',
            field=models.FloatField(default=8, help_text='Standard working hours per day'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='process',
            field=models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], default='machining', max_length=50),
        ),
    ]
