# Generated by Django 6.0.5 on 2026-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_worker_blood_group_worker_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworker',
            name='jw_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
