# Generated by Django 6.0.5 on 2026-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_jobworker_jw_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='extra_allowance',
            field=models.FloatField(default=0),
        ),
    ]
