# Generated by Django 6.0.5 on 2026-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_attendance_extra_allowance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='extra_allowance',
        ),
        migrations.AddField(
            model_name='worker',
            name='monthly_allowance',
            field=models.FloatField(default=0, help_text='Automated monthly allowance added to salary'),
        ),
    ]
