# Generated by Django 6.0.5 on 2026-05-15 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_attendance_extra_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborpayment',
            name='payment_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('ADVANCE', 'Advance'), ('JOB_WORK', 'Job Work Payment'), ('LOAN_REPAYMENT', 'Loan Repayment')], max_length=20),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('emi_amount', models.FloatField(help_text='Standard monthly deduction')),
                ('remaining_balance', models.FloatField()),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.worker')),
            ],
        ),
    ]
