# Generated by Django 6.0.5 on 2026-05-15 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_laborpayment_payment_type_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='job_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.jobworker'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.worker'),
        ),
    ]
