# Generated by Django 6.0.5 on 2026-05-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_loan_job_worker_alter_loan_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborpayment',
            name='payment_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('ADVANCE', 'Advance'), ('NEW_LOAN', 'New Loan'), ('JOB_WORK', 'Job Work Payment'), ('LOAN_REPAYMENT', 'Loan Repayment')], max_length=20),
        ),
    ]
