# Generated by Django 6.0.5 on 2026-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_laborpayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='rejection_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
