# Generated by Django 6.0.5 on 2026-05-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_jobwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('weight_per_piece', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jobwork',
            name='product',
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging'), ('dispatch', 'Dispatch')], max_length=20, null=True)),
                ('to_stage', models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging'), ('dispatch', 'Dispatch')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.DeleteModel(
            name='CastingStock',
        ),
        migrations.DeleteModel(
            name='JobWork',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
