# Generated by Django 6.0.5 on 2026-05-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_remove_jobwork_product_stocktransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='to_stage',
            new_name='stage',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='from_stage',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='direction',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=10),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight_per_piece',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.client'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='job_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.jobworker'),
        ),
    ]
