# Generated by Django 6.0.5 on 2026-05-11 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_client_jobworker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('process', models.CharField(choices=[('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='job_worker',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='heat_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BRASS', 'Brass'), ('MORTAR', 'Mortar'), ('PESTLE', 'Pestle'), ('CHOPPING', 'Chopping Board'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='direction',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stage',
            field=models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging'), ('dispatch', 'Dispatch')], max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.worker'),
        ),
        migrations.DeleteModel(
            name='JobWorker',
        ),
    ]
