# Generated by Django 6.0.5 on 2026-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_worker_remove_stocktransaction_job_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight_per_piece',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
