# Generated by Django 6.0.5 on 2026-05-12 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_stocktransaction_job_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.client",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="machining_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BRASS", "Brass"),
                    ("SS", "Stainless Steel"),
                    ("CI", "Cast Iron"),
                    ("ALUMINIUM", "Aluminium"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="packing_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="polishing_required",
            field=models.BooleanField(default=True),
        ),
    ]
