# Generated by Django 6.0.5 on 2026-05-14 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_item_client_item_machining_required_item_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='weight_per_piece',
            new_name='casting_weight',
        ),
        migrations.AddField(
            model_name='item',
            name='default_machining_jobworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_machining_items', to='inventory.jobworker'),
        ),
        migrations.AddField(
            model_name='item',
            name='machining_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='machining_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobworker',
            name='process',
            field=models.CharField(choices=[('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('casting_entry', 'Casting Entry'), ('machining_out', 'Machining Issue'), ('machining_in', 'Machining Receive'), ('polishing_out', 'Polishing Issue'), ('polishing_in', 'Polishing Receive'), ('packaging_in', 'Packaging Receive'), ('dispatch_out', 'Dispatch Out')], max_length=50),
        ),
    ]
