# Generated by Django 6.0.5 on 2026-05-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_item_default_machining_jobworker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
