# Generated by Django 6.0.5 on 2026-05-14 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_item_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('casting_entry', 'Casting Entry'), ('machining_out', 'Machining Issue'), ('machining_in', 'Machining Receive'), ('polishing_out', 'Polishing Issue'), ('polishing_in', 'Polishing Receive'), ('packaging_in', 'Packaging Receive'), ('dispatch_out', 'Dispatch Out'), ('kitting_consume', 'Assembly Consume'), ('kitting_produce', 'Assembly Produce')], max_length=50),
        ),
        migrations.CreateModel(
            name='ItemComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_sets', to='inventory.item')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.item')),
            ],
            options={
                'unique_together': {('parent_item', 'component_item')},
            },
        ),
    ]
