# Generated by Django 6.0.5 on 2026-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_remove_stocktransaction_job_worker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="casting_required",
            field=models.BooleanField(default=True),
        ),
    ]
