# Generated by Django 6.0.5 on 2026-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_item_casting_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
