# Generated by Django 6.0.5 on 2026-05-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_jobworker_email_jobworker_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemworkerallocation',
            options={'verbose_name': 'Item Worker Rate'},
        ),
        migrations.AlterUniqueTogether(
            name='itemworkerallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemworkerallocation',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_allocations', to='inventory.worker'),
        ),
        migrations.AlterField(
            model_name='itemworkerallocation',
            name='job_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_item_allocations', to='inventory.jobworker'),
        ),
    ]
