# Generated by Django 6.0.5 on 2026-05-18 04:45

from django.db import migrations, models


def populate_defaults(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    Material = apps.get_model('inventory', 'Material')
    
    # Add default categories
    default_categories = ["Brass", "Mortar", "Pestle", "Chopping Board", "Other"]
    for name in default_categories:
        Category.objects.get_or_create(name=name)
        
    # Add default materials
    default_materials = ["Brass", "Stainless Steel", "Cast Iron", "Aluminium"]
    for name in default_materials:
        Material.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_stocktransaction_rejection_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, default='OTHER', max_length=100, null=True),
        ),
        migrations.RunPython(populate_defaults),
    ]
