# Generated by Django 6.0.5 on 2026-05-18 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_category_material_alter_item_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('carton_type', models.CharField(choices=[('SINGLE', 'Single Item'), ('SET', 'Set Item'), ('MIXED', 'Mixed Carton')], default='SINGLE', max_length=20)),
                ('carton_label', models.CharField(blank=True, max_length=200, null=True)),
                ('cleaning', models.BooleanField(default=False)),
                ('labeling', models.BooleanField(default=False)),
                ('packing', models.BooleanField(default=False)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_weight', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('READY', 'In Warehouse'), ('DISPATCHED', 'Dispatched')], default='READY', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartons', to='inventory.client')),
            ],
        ),
        migrations.CreateModel(
            name='CartonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.carton')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_contents', to='inventory.item')),
            ],
        ),
    ]
