# Generated by Django 6.0.5 on 2026-05-22 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_client_is_deleted_item_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCompanyChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inter-Company Challan',
                'verbose_name_plural': 'Inter-Company Challans',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('letterhead_title', models.CharField(blank=True, help_text='Optional custom title for letters', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
            },
        ),
        migrations.CreateModel(
            name='ClientPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(help_text='Committed delivery date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_pos', to='products.client')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_pos', to='client_orders.legalentity')),
            ],
            options={
                'verbose_name': 'Client Purchase Order',
                'verbose_name_plural': 'Client Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='ClientPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_dispatched', models.IntegerField(default=0)),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_orders.clientpo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='products.item')),
            ],
            options={
                'verbose_name': 'Client PO Line Item',
                'verbose_name_plural': 'Client PO Line Items',
            },
        ),
        migrations.CreateModel(
            name='InterCompanyChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField(default=0.0)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_orders.intercompanychallan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challan_items', to='products.item')),
            ],
            options={
                'verbose_name': 'Inter-Company Challan Line Item',
                'verbose_name_plural': 'Inter-Company Challan Line Items',
            },
        ),
        migrations.AddField(
            model_name='intercompanychallan',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_challans', to='client_orders.legalentity'),
        ),
        migrations.AddField(
            model_name='intercompanychallan',
            name='to_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_challans', to='client_orders.legalentity'),
        ),
    ]
