# Generated by Django 6.0.5 on 2026-05-22 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0001_initial'),
        ('products', '0004_warehouse_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='client_record',
            field=models.OneToOneField(blank=True, help_text='The corresponding Client record when this entity acts as a customer to another entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entity', to='products.client'),
        ),
    ]
