# Generated by Django 6.0.5 on 2026-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0002_legalentity_client_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='processes',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of active operational processes (CASTING, MACHINING, POLISHING, PACKAGING, DISPATCH)', max_length=255, null=True),
        ),
    ]
