# Generated by Django 6.0.5 on 2026-05-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0007_maintenancelog_maintenancesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('dispatch_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.client')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField(default=0.0)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.dispatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('external_po_number', models.CharField(help_text="Client's PO Ref Number", max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('promised_date', models.DateField(help_text='Fulfillment Deadline')),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open / Pending'), ('PARTIAL', 'Partially Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='master_data.client')),
            ],
        ),
        migrations.AddField(
            model_name='dispatch',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='orders.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.IntegerField()),
                ('rate_per_piece', models.FloatField(help_text='Agreed contractual rate for this order')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.salesorder')),
            ],
        ),
    ]
