# Generated by Django 6.0.5 on 2026-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='external_po_number',
            field=models.CharField(blank=True, help_text="Client's PO Ref Number", max_length=100, null=True),
        ),
    ]
