# Generated by Django 6.0.5 on 2026-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_salesorder_external_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='rate_per_piece',
            field=models.FloatField(default=0.0, help_text='Agreed contractual rate for this order'),
        ),
    ]
