# Generated by Django 6.0.5 on 2026-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_salesorderitem_rate_per_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
