# Generated by Django 6.0.5 on 2026-05-28 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_sets', to='master_data.item')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='master_data.item')),
            ],
            options={
                'unique_together': {('parent_item', 'component_item')},
            },
        ),
    ]
