# Generated by Django 6.0.5 on 2026-05-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_category_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='REGULAR', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, default='OTHER', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
