# Generated by Django 6.0.5 on 2026-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_client_email_client_gst_number_item_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
