# Generated by Django 6.0.5 on 2026-05-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_client_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='handles_casting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='handles_machining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='handles_packaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='handles_polishing',
            field=models.BooleanField(default=False),
        ),
    ]
