# Generated by Django 6.0.5 on 2026-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_legalentity_handles_casting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('backup', 'Auto-Backup'), ('delete', 'Auto-Delete Purge'), ('audit_fail', 'Safety Audit Blocked'), ('restore', 'Database Restoration'), ('reset', 'Factory Reset')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('auto_backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('backup_retention_count', models.IntegerField(default=10)),
                ('last_backup_run', models.DateTimeField(blank=True, null=True)),
                ('auto_delete_enabled', models.BooleanField(default=False)),
                ('auto_delete_frequency', models.CharField(choices=[('4_months', 'Every 4 Months'), ('6_months', 'Half-Year (6 Months)'), ('1_year', 'Every 1 Year')], default='6_months', max_length=20)),
                ('last_delete_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Maintenance Settings',
                'verbose_name_plural': 'Maintenance Settings',
            },
        ),
    ]
