# Generated by Django 6.0.5 on 2026-05-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_maintenancelog_maintenancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='packing_preference',
            field=models.CharField(choices=[('BOX_PREF', 'Box Lot Preferred & Flexible'), ('REG_PREF', 'Regular Preferred & Flexible'), ('BOX_STRICT', 'Strict Box Lot Only'), ('REG_STRICT', 'Strict Regular Only'), ('ANY', 'Fully Flexible / Any')], default='ANY', max_length=20),
        ),
    ]
