# Generated by Django 6.0.5 on 2026-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_client_packing_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='OTHER', max_length=50),
        ),
    ]
