# Generated by Django 6.0.5 on 2026-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BRASS', 'Brass'), ('MORTAR', 'Mortar'), ('PESTLE', 'Pestle'), ('CHOPPING_BOARD', 'Chopping Board'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
