# Generated by Django 6.0.5 on 2026-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_alter_item_code_alter_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_gu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Gujarati)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_gu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Gujarati)'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Hindi)'),
        ),
    ]
