# Generated by Django 6.0.5 on 2026-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_category_name_gu_category_name_hi_item_name_gu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_gu',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_gu',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_hi',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='OTHER', max_length=50),
        ),
    ]
