# Generated by Django 6.0.5 on 2026-07-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_remove_category_name_gu_remove_category_name_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='is_weekly_off_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='weekly_off',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'None')], default=6),
        ),
    ]
