# Generated by Django 6.0.5 on 2026-07-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_legalentity_is_weekly_off_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_lot_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='default_lot_with_box',
            field=models.IntegerField(default=1),
        ),
    ]
