# Generated by Django 6.0.5 on 2026-07-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_client_default_lot_size_client_default_lot_with_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='default_lot_size',
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_lot_with_box',
        ),
    ]
