# Generated by Django 6.0.5 on 2026-07-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_remove_client_default_lot_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_casting_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='min_machining_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='min_polishing_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='min_ready_stock',
            field=models.IntegerField(default=0),
        ),
    ]
