# Generated by Django 6.0.5 on 2026-07-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_item_min_casting_stock_item_min_machining_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_raw_material',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_items', to='master_data.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='yield_pcs_per_unit',
            field=models.FloatField(default=1.0),
        ),
    ]
