# Generated by Django 6.0.5 on 2026-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_item_is_raw_material_item_raw_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='yield_unit',
            field=models.CharField(choices=[('PCS', 'Pieces (Pcs)'), ('KG', 'Kilograms (Kg)'), ('CHAAD', 'Pipes (Chaad)'), ('FEET', 'Feet (Ft)'), ('INCH', 'Inches (In)')], default='PCS', max_length=20),
        ),
    ]
