# Generated by Django 6.0.5 on 2026-07-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_item_yield_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='yield_unit',
        ),
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.CharField(choices=[('PCS', 'Pieces (Pcs)'), ('KG', 'Kilograms (Kg)'), ('CHAAD', 'Pipes (Chaad)'), ('FEET', 'Feet (Ft)'), ('INCH', 'Inches (In)'), ('CM', 'Centimeters (Cm)'), ('MM', 'Millimeters (Mm)')], default='PCS', max_length=20),
        ),
    ]
