# Generated by Django 6.0.5 on 2026-07-22 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_remove_item_yield_unit_item_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='master_data.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_balances', to='master_data.warehouse')),
            ],
            options={
                'verbose_name': 'Item Stock Balance',
                'verbose_name_plural': 'Item Stock Balances',
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
