# Generated by Django 6.0.5 on 2026-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_client_uuid_legalentity_uuid_itemstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancesettings',
            name='last_delete_run',
        ),
        migrations.AddField(
            model_name='maintenancesettings',
            name='device_security_mode',
            field=models.CharField(choices=[('DEV_AUTO_APPROVE', '🟢 Dev Auto-Approve (Local/Dev Networks Auto-Approved)'), ('FACTORY_LOCAL_AUTO_APPROVE', '🟡 Factory Wi-Fi Auto-Approve (Local LAN Approved, WAN Pending)'), ('STRICT_SECURITY', '🔴 Strict Production (Every Non-Admin Device Requires Approval)'), ('DISABLED', '⚪ Security Interceptor Disabled')], default='DEV_AUTO_APPROVE', max_length=30),
        ),
    ]
