# Generated by Django 6.0.5 on 2026-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_remove_maintenancesettings_last_delete_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancesettings',
            name='factory_latitude',
            field=models.FloatField(default=22.3039, help_text='Factory GPS Latitude (e.g. 22.3039)'),
        ),
        migrations.AddField(
            model_name='maintenancesettings',
            name='factory_longitude',
            field=models.FloatField(default=70.8022, help_text='Factory GPS Longitude (e.g. 70.8022)'),
        ),
        migrations.AddField(
            model_name='maintenancesettings',
            name='geofence_enforce_block',
            field=models.BooleanField(default=False, help_text='Strictly block non-admin logins outside factory radius'),
        ),
        migrations.AddField(
            model_name='maintenancesettings',
            name='geofence_radius_meters',
            field=models.IntegerField(default=500, help_text='Authorized radius in meters around factory'),
        ),
    ]
