# Generated by Django 6.0.5 on 2026-05-21 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('process', models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('jw_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary_model', models.CharField(choices=[('DAILY', 'Daily Wage'), ('FIXED', 'Monthly Fixed'), ('HOURLY', 'Hourly/Time Based')], default='DAILY', max_length=20)),
                ('daily_rate', models.FloatField(default=0, help_text='Rate per day for Daily Wage workers')),
                ('monthly_fixed_salary', models.FloatField(default=0, help_text='Fixed monthly salary for Fixed model')),
                ('overtime_rate', models.FloatField(default=0, help_text='Rate per hour of overtime')),
                ('monthly_allowance', models.FloatField(default=0, help_text='Automated monthly allowance added to salary')),
                ('process', models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], default='machining', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('standard_shift_hours', models.FloatField(default=8, help_text='Standard working hours per day')),
                ('identity_number', models.CharField(blank=True, help_text='Aadhar / Govt ID', max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20)),
                ('overtime_hours', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='workforce.worker')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
