# Generated by Django 6.0.5 on 2026-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworker',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
