# Generated by Django 6.0.5 on 2026-05-21 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('casting_entry', 'Casting Entry'), ('machining_out', 'Machining Issue'), ('machining_in', 'Machining Receive'), ('polishing_out', 'Polishing Issue'), ('polishing_in', 'Polishing Receive'), ('packaging_in', 'Packaging Receive'), ('dispatch_out', 'Dispatch Out'), ('kitting_consume', 'Assembly Consume'), ('kitting_produce', 'Assembly Produce')], max_length=50)),
                ('heat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('rejection_quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('lot_quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.client')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_transactions', to='products.warehouse')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.jobworker')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_transactions', to='products.warehouse')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.worker')),
            ],
        ),
    ]
