# Generated by Django 6.0.5 on 2026-05-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '__first__'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='client_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='client_orders.clientpo'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='inter_company_challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='client_orders.intercompanychallan'),
        ),
    ]
