# Generated by Django 6.0.5 on 2026-05-28 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_jobworker_worker'),
        ('master_data', '0002_itemcomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('carton_type', models.CharField(choices=[('SINGLE', 'Single Item'), ('SET', 'Set Item'), ('MIXED', 'Mixed Carton')], default='SINGLE', max_length=20)),
                ('carton_label', models.CharField(blank=True, max_length=200, null=True)),
                ('cleaning', models.BooleanField(default=False)),
                ('labeling', models.BooleanField(default=False)),
                ('packing', models.BooleanField(default=False)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_weight', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('READY', 'In Warehouse'), ('DISPATCHED', 'Dispatched')], default='READY', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartons', to='master_data.client')),
            ],
        ),
        migrations.CreateModel(
            name='CartonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.carton')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carton_contents', to='master_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemWorkerAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_piece', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_allocations', to='master_data.item')),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_item_allocations', to='authentication.jobworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_allocations', to='authentication.worker')),
            ],
            options={
                'verbose_name': 'Item Worker Rate',
                'verbose_name_plural': 'Item Worker Rates',
            },
        ),
        migrations.CreateModel(
            name='LaborPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('SALARY', 'Salary'), ('ADVANCE', 'Advance'), ('NEW_LOAN', 'New Loan'), ('JOB_WORK', 'Job Work Payment'), ('LOAN_REPAYMENT', 'Loan Repayment')], max_length=20)),
                ('payment_mode', models.CharField(default='CASH', max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.jobworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('emi_amount', models.FloatField(help_text='Standard monthly deduction')),
                ('remaining_balance', models.FloatField()),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='authentication.jobworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='authentication.worker')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('casting_entry', 'Casting Entry'), ('machining_out', 'Machining Issue'), ('machining_in', 'Machining Receive'), ('polishing_out', 'Polishing Issue'), ('polishing_in', 'Polishing Receive'), ('packaging_in', 'Packaging Receive'), ('dispatch_out', 'Dispatch Out'), ('kitting_consume', 'Assembly Consume'), ('kitting_produce', 'Assembly Produce')], max_length=50)),
                ('heat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('rejection_quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('lot_quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.client')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_transactions', to='master_data.warehouse')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.jobworker')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_transactions', to='master_data.warehouse')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20)),
                ('overtime_hours', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='authentication.worker')),
            ],
            options={
                'verbose_name_plural': 'Attendance Logs',
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
