# Generated by Django 6.0.5 on 2026-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('casting_entry', 'Casting Entry'), ('machining_out', 'Machining Issue'), ('machining_in', 'Machining Receive'), ('polishing_out', 'Polishing Issue'), ('polishing_in', 'Polishing Receive'), ('packaging_in', 'Packaging Receive'), ('dispatch_out', 'Dispatch Out'), ('kitting_consume', 'Assembly Consume'), ('kitting_produce', 'Assembly Produce'), ('stock_adjustment', 'Stock Adjustment')], max_length=50),
        ),
    ]
