# Generated by Django 6.0.5 on 2026-06-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_dispatch_dispatch_date'),
        ('production', '0002_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carton',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartons', to='orders.salesorder'),
        ),
    ]
