# Generated by Django 6.0.5 on 2026-07-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_remove_category_name_gu_remove_category_name_hi_and_more'),
        ('production', '0004_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this holiday is paid for daily-wage workers.')),
                ('company', models.ForeignKey(blank=True, help_text='The company this holiday applies to. Leave empty for a global holiday.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='master_data.legalentity')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'company')},
            },
        ),
    ]
