# Generated by Django 6.0.5 on 2026-07-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_attendance_status_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_working_day_override',
            field=models.BooleanField(default=False, help_text='If checked, this day is treated as a regular working day, overriding any company weekly off configuration.'),
        ),
    ]
