# Generated by Django 6.0.5 on 2026-07-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_holiday_is_working_day_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='actual_scale_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
