# Generated by Django 6.0.5 on 2026-07-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='linked_consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_production', to='production.stocktransaction'),
        ),
    ]
