# Generated by Django 6.0.5 on 2026-08-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_attendance_uuid_carton_uuid_holiday_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborpayment',
            name='settlement_period',
            field=models.CharField(blank=True, help_text='Y-m period being settled e.g. 2026-07', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='laborpayment',
            name='payment_type',
            field=models.CharField(choices=[('SALARY', 'Salary Settlement'), ('ADVANCE', 'Advance Paid'), ('NEW_LOAN', 'New Loan Given'), ('JOB_WORK', 'Job Work Settlement'), ('LOAN_REPAYMENT', 'Loan Repayment')], max_length=20),
        ),
    ]
