# Generated by Django 6.0.5 on 2026-08-08 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_workerratehistory'),
        ('master_data', '0021_client_uuid_legalentity_uuid_itemstock'),
        ('production', '0011_laborpayment_settlement_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWorkerRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_piece', models.FloatField(default=0.0)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='production.itemworkerallocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='master_data.item')),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_rate_history', to='authentication.jobworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_rate_history', to='authentication.worker')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
