# Generated by Django 6.0.5 on 2026-08-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_jobworker_company'),
        ('master_data', '0022_remove_maintenancesettings_last_delete_run_and_more'),
        ('production', '0012_itemworkerratehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemworkerallocation',
            name='job_worker',
        ),
        migrations.RemoveField(
            model_name='itemworkerratehistory',
            name='job_worker',
        ),
        migrations.RemoveField(
            model_name='laborpayment',
            name='job_worker',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='job_worker',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='job_worker',
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'worker'], name='production__date_85e1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['worker', 'date'], name='production__worker__b8be9d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='production__date_3e1152_idx'),
        ),
        migrations.AddIndex(
            model_name='itemworkerallocation',
            index=models.Index(fields=['worker', 'item'], name='production__worker__b7827a_idx'),
        ),
        migrations.AddIndex(
            model_name='itemworkerratehistory',
            index=models.Index(fields=['worker', 'item', 'effective_from'], name='production__worker__bfc252_idx'),
        ),
        migrations.AddIndex(
            model_name='itemworkerratehistory',
            index=models.Index(fields=['worker', 'effective_from'], name='production__worker__74a6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='laborpayment',
            index=models.Index(fields=['worker', 'date'], name='production__worker__f820d7_idx'),
        ),
        migrations.AddIndex(
            model_name='laborpayment',
            index=models.Index(fields=['settlement_period'], name='production__settlem_10ea7d_idx'),
        ),
        migrations.AddIndex(
            model_name='laborpayment',
            index=models.Index(fields=['date', 'payment_type'], name='production__date_0ae7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['item', 'transaction_type'], name='production__item_id_510ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='production__transac_d6aa57_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['worker', 'transaction_type'], name='production__worker__811825_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['client', 'transaction_type'], name='production__client__237f08_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['from_warehouse', 'to_warehouse'], name='production__from_wa_002b9d_idx'),
        ),
    ]
