# Generated by Django 6.0.5 on 2026-08-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_delete_jobworker'),
        ('master_data', '0022_remove_maintenancesettings_last_delete_run_and_more'),
        ('production', '0013_remove_itemworkerallocation_job_worker_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemworkerallocation',
            unique_together={('worker', 'item')},
        ),
    ]
