# Generated by Django 6.0.5 on 2026-05-21 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='OTHER', max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, default='OTHER', max_length=100, null=True)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(default='REGULAR', max_length=100)),
                ('casting_weight', models.FloatField(default=0)),
                ('machining_weight', models.FloatField(default=0)),
                ('lot_size', models.IntegerField(default=0)),
                ('lot_with_box', models.IntegerField(default=0)),
                ('process', models.CharField(blank=True, choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50, null=True)),
                ('casting_required', models.BooleanField(default=True)),
                ('machining_required', models.BooleanField(default=True)),
                ('polishing_required', models.BooleanField(default=True)),
                ('packing_required', models.BooleanField(default=True)),
                ('rate_per_piece', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.client')),
            ],
        ),
        migrations.CreateModel(
            name='ItemComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_sets', to='products.item')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.item')),
            ],
            options={
                'unique_together': {('parent_item', 'component_item')},
            },
        ),
    ]
