# Generated by Django 6.0.5 on 2026-05-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '__first__'),
        ('products', '0003_client_is_deleted_item_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='client_orders.legalentity'),
        ),
    ]
