# Generated by Django 6.0.5 on 2026-05-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0002_legalentity_client_record'),
        ('products', '0004_warehouse_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company this client belongs to. If blank, it is a shared client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clients', to='client_orders.legalentity'),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company this item belongs to. If blank, it is a shared item in the casting pipeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_items', to='client_orders.legalentity'),
        ),
    ]
