# Generated by Django 6.0.5 on 2026-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0002_legalentity_client_record'),
        ('products', '0005_client_company_item_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.AddField(
            model_name='client',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='The companies this client belongs to. If empty, the client is global.', related_name='owned_clients', to='client_orders.legalentity'),
        ),
        migrations.AddField(
            model_name='item',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='The companies this item belongs to. If empty, the item is global.', related_name='owned_items', to='client_orders.legalentity'),
        ),
    ]
