# Generated by Django 6.0.5 on 2026-05-21 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWorkerAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_piece', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_allocations', to='products.item')),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_item_allocations', to='workforce.jobworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_allocations', to='workforce.worker')),
            ],
            options={
                'verbose_name': 'Item Worker Rate',
            },
        ),
        migrations.CreateModel(
            name='LaborPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('SALARY', 'Salary'), ('ADVANCE', 'Advance'), ('NEW_LOAN', 'New Loan'), ('JOB_WORK', 'Job Work Payment'), ('LOAN_REPAYMENT', 'Loan Repayment')], max_length=20)),
                ('payment_mode', models.CharField(default='CASH', max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.jobworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('emi_amount', models.FloatField(help_text='Standard monthly deduction')),
                ('remaining_balance', models.FloatField()),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='workforce.jobworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='workforce.worker')),
            ],
        ),
    ]
