# Generated by Django 6.0.5 on 2026-05-28 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('master_data', '0002_itemcomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('process', models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('jw_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_workers', to='master_data.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary_model', models.CharField(choices=[('DAILY', 'Daily Wage'), ('FIXED', 'Monthly Fixed'), ('HOURLY', 'Hourly/Time Based')], default='DAILY', max_length=20)),
                ('daily_rate', models.FloatField(default=0)),
                ('monthly_fixed_salary', models.FloatField(default=0)),
                ('overtime_rate', models.FloatField(default=0)),
                ('monthly_allowance', models.FloatField(default=0)),
                ('process', models.CharField(choices=[('casting', 'Casting'), ('machining', 'Machining'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], default='machining', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('standard_shift_hours', models.FloatField(default=8)),
                ('identity_number', models.CharField(blank=True, help_text='Aadhar / Govt ID', max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='master_data.legalentity')),
            ],
        ),
    ]
