# Generated by Django 6.0.5 on 2026-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_jobworker_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworker',
            name='casting_rate_per_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='worker',
            name='casting_rate_per_kg',
            field=models.FloatField(default=0.0),
        ),
    ]
