# Generated by Django 6.0.5 on 2026-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_jobworker_casting_rate_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworker',
            name='name_gu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Gujarati)'),
        ),
        migrations.AddField(
            model_name='jobworker',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='worker',
            name='name_gu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Gujarati)'),
        ),
        migrations.AddField(
            model_name='worker',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Hindi)'),
        ),
    ]
