# Generated by Django 6.0.5 on 2026-07-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_jobworker_name_gu_jobworker_name_hi_worker_name_gu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobworker',
            name='name_gu',
        ),
        migrations.RemoveField(
            model_name='jobworker',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='name_gu',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='name_hi',
        ),
    ]
