# Generated by Django 6.0.5 on 2026-07-22 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_jobworker_name_gu_remove_jobworker_name_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='jw_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional portal login account associated with this worker or job worker.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worker',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('IN_HOUSE', 'In-House Worker'), ('JOB_WORKER', 'External Job Worker')], default='IN_HOUSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('MANAGER', 'Production Manager'), ('OPERATOR', 'Casting Operator'), ('ACCOUNTANT', 'Accounts Manager'), ('JOB_WORKER', 'External Job Worker')], default='OPERATOR', max_length=20),
        ),
    ]
