# Generated by Django 6.0.5 on 2026-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_worker_address_worker_email_worker_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_financials',
            field=models.BooleanField(default=True, help_text='Can view rates, costs, wages, and monetary figures'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Hierarchical Permission Tree Matrix (JSON)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin / Owner'), ('CASTING_MGR', 'Foundry Casting Manager'), ('MACHINING_MGR', 'Machining & Polishing Supervisor'), ('PACKAGING_MGR', 'Packaging & Warehouse Manager'), ('SALES_ADMIN', 'Sales & Customer PO Admin'), ('ACCOUNTANT', 'Accounts & Payroll Manager'), ('AUDITOR', 'Auditor (Read-Only)'), ('CUSTOM', 'Custom Role Matrix')], default='CUSTOM', max_length=30),
        ),
    ]
