# Generated by Django 6.0.5 on 2026-08-07 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_can_view_financials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Unique UUID device fingerprint string', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Device label (e.g. Casting Floor Tablet #1)', max_length=150)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='True if approved by Admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_devices', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorized Device',
                'verbose_name_plural': 'Authorized Devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
