# Generated by Django 6.0.5 on 2026-08-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_authorizeddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='allowance_calc_mode',
            field=models.CharField(choices=[('FIXED', 'Full Fixed Monthly Allowance'), ('PRO_RATA', 'Pro-Rata Attendance Based (Working Days)')], default='FIXED', help_text='Full fixed allowance vs pro-rata attendance divided by net working days', max_length=20),
        ),
    ]
