# Generated by Django 6.0.5 on 2026-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_worker_allowance_calc_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fixed_salary_calc_mode',
            field=models.CharField(choices=[('PRO_RATA', 'Pro-Rata (Divided by Net Working Days)'), ('FIXED_FULL', 'Full Fixed Monthly (No Absent Cut)'), ('CALENDAR_30', '30-Day Fixed Rate (Salary / 30)')], default='PRO_RATA', help_text='Pro-rata absent cut vs full fixed salary vs 30-day rate', max_length=20),
        ),
    ]
