# Generated by Django 6.0.5 on 2026-08-08 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_worker_fixed_salary_calc_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.FloatField(default=0.0)),
                ('monthly_fixed_salary', models.FloatField(default=0.0)),
                ('overtime_rate', models.FloatField(default=0.0)),
                ('monthly_allowance', models.FloatField(default=0.0)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='authentication.worker')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
