# Generated by Django 6.0.5 on 2026-08-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_workerratehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeddevice',
            name='brand_model',
            field=models.CharField(blank=True, help_text='e.g. Apple iPhone, Samsung Galaxy Tab', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='browser_info',
            field=models.CharField(blank=True, help_text='e.g. Safari, Chrome', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='device_type',
            field=models.CharField(default='MOBILE', help_text='MOBILE, TABLET, DESKTOP', max_length=20),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='hardware_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='os_info',
            field=models.CharField(blank=True, help_text='e.g. iOS 17.5, Android 14, Windows 11', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why device was rejected/blocked by Admin', null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected / Blocked')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
