# Generated by Django 6.0.5 on 2026-08-09 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_authorizeddevice_brand_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_scope', models.CharField(choices=[('FACTORY_LOCAL', '🏢 Factory Local Wi-Fi'), ('EXTERNAL_REMOTE', '🌐 External Remote Network')], default='FACTORY_LOCAL', max_length=20)),
                ('event_type', models.CharField(choices=[('CREATE', '➕ Data Created'), ('UPDATE', '✏️ Data Updated'), ('DELETE', '🗑 Data Deleted'), ('SECURITY_BLOCKED', '🚫 Permission Blocked'), ('SECURITY_REJECTED', '🛑 Device Access Rejected'), ('AUTH_LOGIN', '🔑 User Login'), ('AUTH_FAILED', '⚠️ Login Failed'), ('PAGE_VIEW', '👁 Page Navigation')], db_index=True, max_length=30)),
                ('module_name', models.CharField(db_index=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=60, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('changes_json', models.JSONField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='authentication.authorizeddevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Audit Log',
                'verbose_name_plural': 'System Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserLiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.CharField(default='Dashboard', max_length=100)),
                ('current_path', models.CharField(default='/', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_scope', models.CharField(default='FACTORY_LOCAL', max_length=20)),
                ('last_heartbeat', models.DateTimeField(auto_now=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.authorizeddevice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Live Activity',
                'verbose_name_plural': 'User Live Activities',
                'ordering': ['-last_heartbeat'],
            },
        ),
    ]
