# Generated by Django 6.0.5 on 2026-08-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_systemauditlog_userliveactivity'),
        ('master_data', '0021_client_uuid_legalentity_uuid_itemstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_companies',
            field=models.ManyToManyField(blank=True, help_text='Explicit legal companies this user is allowed to access and switch between.', related_name='allowed_users', to='master_data.legalentity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_global_access',
            field=models.BooleanField(default=False, help_text='True if granted Global / All Access (Owner Portal).'),
        ),
    ]
