# Generated by Django 6.0.5 on 2026-08-10 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_allowed_companies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySettlementLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_str', models.CharField(db_index=True, help_text='YYYY-MM e.g. 2026-07', max_length=7)),
                ('is_locked', models.BooleanField(default=True, help_text='True if settlement is frozen')),
                ('locked_earnings', models.FloatField(default=0.0, help_text='Frozen earned wages at time of settlement')),
                ('locked_paid', models.FloatField(default=0.0, help_text='Frozen total paid at time of settlement')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_locks', to='authentication.worker')),
            ],
            options={
                'verbose_name': 'Monthly Settlement Lock',
                'verbose_name_plural': 'Monthly Settlement Locks',
                'unique_together': {('worker', 'month_str')},
            },
        ),
    ]
