# Generated by Django 6.0.5 on 2026-08-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_monthlysettlementlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobworker',
            name='company',
        ),
    ]
