# Generated by Django 6.0.5 on 2026-08-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_jobworker_company'),
        ('production', '0013_remove_itemworkerallocation_job_worker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobWorker',
        ),
    ]
