# Generated by Django 6.0.5 on 2026-09-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_delete_jobworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Session inactivity timeout in minutes (default: 60)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timeout_logout_mode',
            field=models.CharField(choices=[('POPUP_WARNING', 'Friendly Warning (60s Countdown)'), ('INSTANT_LOGOUT', 'Instant Logout')], default='POPUP_WARNING', help_text='Inactivity logout behavior (popup countdown vs instant logout)', max_length=20),
        ),
    ]
