# Generated by Django 6.0.5 on 2026-09-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_customuser_session_timeout_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRecoveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(blank=True, default='', help_text='Hashed Master Recovery Key', max_length=255)),
                ('key_hint', models.CharField(blank=True, help_text='Hint for admin (e.g. Ends with ...)', max_length=60, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Recovery Configuration',
            },
        ),
    ]
