# Generated by Django 6.0.5 on 2026-09-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_adminrecoveryconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrecoveryconfig',
            name='last_security_alerts_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
