# Generated by Django 6.0.5 on 2026-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_adminrecoveryconfig_last_security_alerts_cleared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeddevice',
            name='battery_level',
            field=models.IntegerField(blank=True, help_text='Battery percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='connection_type',
            field=models.CharField(blank=True, help_text='e.g. 4G, 5G, Wi-Fi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='gpu_renderer',
            field=models.CharField(blank=True, help_text='e.g. Apple A17 Pro GPU, Adreno 740', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='is_charging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Latitude', null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='location_accuracy_meters',
            field=models.FloatField(blank=True, help_text='GPS Accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Longitude', null=True),
        ),
        migrations.AddField(
            model_name='authorizeddevice',
            name='screen_resolution',
            field=models.CharField(blank=True, help_text='e.g. 1179x2556 @ 3x', max_length=50, null=True),
        ),
    ]
